const LOAD_TICKETS = "LOAD_TICKETS"
const EXTRACT_ALL_TICKETS = "EXTRACT_ALL_TICKETS"
const EXTRACT_MY_ACCOUNT = "EXTRACT_MY_ACCOUNT"
const EDIT_EVALUATIONS = "EDIT_EVALUATIONS"
const EDIT_CONDITION = "EDIT_CONDITION"
const ORDER_ASC = "ORDER_ASC"
const ORDER_DESC = "ORDER_DESC"

const Command = { LOAD_TICKETS, EXTRACT_ALL_TICKETS, EXTRACT_MY_ACCOUNT, EDIT_EVALUATIONS, EDIT_CONDITION, ORDER_ASC, ORDER_DESC };
export default Command;